// Mechanical import of the original renderer. No runtime eval in the card.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { parse } from 'yaml';
const strip = s => s.replace(/\/\*[\s\S]*?\*\//g, '').replace(/^\s*\/\/.*$/gm, '').replace(/\n\s*\n/g, '\n');
const path = process.argv[2];
let reference;
if (path) {
  const raw = readFileSync(path, 'utf8'), card = parse(raw);
  reference = { sha256: createHash('sha256').update(raw).digest('hex'), fields: {}, css: strip(card.extra_styles) };
  for (const [name, code] of Object.entries(card.custom_fields)) reference.fields[name] = strip(code.trim().slice(3, -3));
  mkdirSync('reference', { recursive: true });
  writeFileSync('reference/local-renderer.json', JSON.stringify(reference, null, 2) + '\n');
} else reference = JSON.parse(readFileSync('reference/local-renderer.json', 'utf8'));
let out = '// @ts-nocheck\n// Generated by scripts/port-local.mjs from reference/local-renderer.json.\n// Original layout and strings retained; globals and inline handlers removed.\nexport function renderLocal(variables, states, hass) {\n const window = {};\n';
for (const [name, original] of Object.entries(reference.fields)) {
  let code = original;
  if (name === 'heros') {
    const start = code.indexOf("if (typeof hass");
    const end = code.indexOf("var BLEU");
    code = code.slice(0, start) + `var esc = s => String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/\"/g, '&quot;');\nwindow.meGeste = id => id ? ' data-entity=\"' + esc(id) + '\" role=\"button\" tabindex=\"0\"' : '';\n` + code.slice(end);
    code = code.replace("ouvrants: 'FERMER', ", '');
  }
  code = code.replace(/var ec = V\.ent_confort[^;]+;/g, '').replace(/var poids = \(ec[^;]+;/g, "var poids = ea.attributes.air_poids || 'neutre';");
  code = code.replace(/var geste = V\.page_air[\s\S]*?: '';/, "var geste = V.page_air ? ' data-nav=\"' + esc(V.page_air) + '\" role=\"link\" tabindex=\"0\"' : window.meGeste(V.ent_air);");
  code = code.replace("(p.ico || 'mdi:flower-pollen')", "esc(p.ico || 'mdi:flower-pollen')");
  // Never borrow ventilation recommendations from a removed integration.
  code = code.replace(/var cre = String\(A\.creneau \|\| ''\);/g, "var cre = '';" );
  out += ` function ${name}() {\n${code}\n }\n`;
}
out += ' return {' + Object.keys(reference.fields).map(n => `${n}: ${n}()`).join(', ') + '};\n}\n';
writeFileSync('src/local-renderer.ts', out);
const css = reference.css.replaceAll('[onclick]', ':is([data-entity], [data-nav])');
writeFileSync('src/local-styles.ts', '// Generated: exact original CSS apart from event attribute selectors.\nexport const localStyles = ' + JSON.stringify(css) + ';\n');
if (process.argv[3]) {
  const raw = readFileSync(process.argv[3], 'utf8'), template = parse(raw)[1];
  const E = Object.fromEntries(Object.keys(template.variables.E).map(key => [key,
    key.startsWith('foudre') || key === 'confort' ? '' : key === 'meteo' ? 'weather.test' : `sensor.${key}`]));
  writeFileSync('reference/local-template.json', JSON.stringify({ sha256: createHash('sha256').update(raw).digest('hex'),
    variables: { ...template.variables, E }, attributes: template.sensor[0].attributes }, null, 2) + '\n');
}
