// Mechanical import of the original renderer. No runtime eval in the card.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { parse } from 'yaml';
const strip = s => s.replace(/\/\*[\s\S]*?\*\//g, '').replace(/^\s*\/\/.*$/gm, '').replace(/\n\s*\n/g, '\n');
const path = process.argv[2];
let reference;
if (path) {
  const raw = readFileSync(path, 'utf8'), card = parse(raw);
  reference = { sha256: createHash('sha256').update(raw).digest('hex'), fields: {}, css: strip(card.extra_styles) };
  for (const [name, code] of Object.entries(card.custom_fields)) reference.fields[name] = strip(code.trim().slice(3, -3));
  mkdirSync('reference', { recursive: true });
  writeFileSync('reference/local-renderer.json', JSON.stringify(reference, null, 2) + '\n');
} else reference = JSON.parse(readFileSync('reference/local-renderer.json', 'utf8'));
let out = '// @ts-nocheck\n// Generated by scripts/port-local.mjs from reference/local-renderer.json.\n// Original layout and strings retained; globals and inline handlers removed.\nexport function renderLocal(variables, states, hass) {\n const window = {};\n';
for (const [name, original] of Object.entries(reference.fields)) {
  let code = original;
  if (name === 'heros') {
    const start = code.indexOf("if (typeof hass");
    const end = code.indexOf("var BLEU");
    code = code.slice(0, start) + `var esc = s => String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/\"/g, '&quot;');\nwindow.meGeste = id => id ? ' data-entity=\"' + esc(id) + '\" role=\"button\" tabindex=\"0\"' : '';\n` + code.slice(end);
    code = code.replace("ouvrants: 'FERMER', ", '');
    // Optional smart brief changes only the hero; the reference mode remains intact.
    code = code.replace('var vc = NIV[niveau] || BLEU;', 'var vc = V.brief ? V.brief.rgb : NIV[niveau] || BLEU;');
    code = code.replace("var ico = meta ? meta.i : 'mdi:thermometer';", "var ico = V.brief ? V.brief.icon : meta ? meta.i : 'mdi:thermometer';");
    code = code.replace("var badge = ALERTE[String(A.alerte || '')] || '';", "var badge = V.brief ? V.brief.label : ALERTE[String(A.alerte || '')] || '';");
    code = code.replace('if (V.lieu) sous =', 'if (V.lieu && !V.brief) sous =');
    code = code.replace("var mesure = String(A.cond_source || '') === 'station';", "var mesure = !V.brief && String(A.cond_source || '') === 'station';");
    code = code.replace("h +=     '<span class=\"me-cur\"", `if (V.dashboard) h += '<strong class="nw-feels-value" style="left:clamp(42px,' + pRes.toFixed(1) + '%,calc(100% - 42px))">' + fr(res, 1) + '<small>°C</small></strong>';\n  h +=     '<span class="me-cur"`);
    code = code.replace("pastille('mdi:water-percent', 'humidex',", "pastille('mdi:water-percent', V.dashboard ? 'base humidex' : 'humidex',");
  }
  if (name === 'bilan') code = code.replace("ligne('7 jours'", "ligne('Cette semaine'").replace("ligne('30 jours'", "ligne('Ce mois'");
  if (name === 'courbe') code = code.replace(
    `'<span class="me-jourl" style="left:' + xd.toFixed(2)\n             + '%;">DEMAIN</span>'`,
    `'<span class="me-jourl" style="left:clamp(0px,' + xd.toFixed(2)\n             + '%,calc(100% - 48px));">DEMAIN</span>'`);
  if (name === 'jours') code = code.replace("+ lignes + '</div>';", `+ (V.dashboard ? '<div class="me-j nw-week-labels" role="group" aria-label="Colonnes : température minimale et maximale en degrés Celsius, pluie en millimètres"><span class="me-jn"></span><span class="me-ji"></span><span class="me-jmin">Min<small>°C</small></span><span class="me-jbar"></span><span class="me-jmax">Max<small>°C</small></span><span class="me-jp">Pluie<small>mm</small></span></div>' : '') + lignes + '</div>';`);
  // Indoor air belongs to another card; keep its removal reproducible when regenerating.
  code = code.replace(/  var ea = V\.ent_air[\s\S]*?\n  }\n/g, '');
  code = code.replace(/var ec = V\.ent_confort[^;]+;/g, '').replace(/var poids = \(ec[^;]+;/g, "var poids = ea.attributes.air_poids || 'neutre';");
  code = code.replace(/var geste = V\.page_air[\s\S]*?: '';/, "var geste = V.page_air ? ' data-nav=\"' + esc(V.page_air) + '\" role=\"link\" tabindex=\"0\"' : window.meGeste(V.ent_air);");
  code = code.replace("(p.ico || 'mdi:flower-pollen')", "esc(p.ico || 'mdi:flower-pollen')");
  if (name === 'tuiles') {
    code = code.replace("var out = '';", `var out = V.dashboard ? '<div class="me-tu" style="--tc:var(--mush-rgb-blue,61,155,233)"' + window.meGeste(SRC.t_ext) + '><div class="me-tuic"><ha-icon icon="mdi:thermometer"></ha-icon></div><div class="me-tut"><span class="nw-metric-name">Température</span><span class="me-tuv">' + esc(fr(nb(A.t_ext), 1)) + '<i>°C</i></span><span class="me-tul">' + (nb(A.ressenti) === null ? 'ressenti indisponible' : 'ressenti ' + esc(fr(nb(A.ressenti), 1)) + ' °C') + '</span><span class="me-tus">' + (nb(A.t_ext) === null ? 'température indisponible' : esc(A.perception || 'au thermomètre')) + '</span></div></div>' : '';`);
    code = code.replace("esc(A.perception || 'au thermomètre')", "esc(A.perception || (V.adaptive && !V.configured?.temperature_entity ? 'température du bulletin' : 'au thermomètre'))");
    code = code.replace('var vv = nb(A.vent), vg = nb(A.rafales), vd = nb(A.vent_deg);', `var vv = nb(A.vent), vg = nb(A.rafales), vd = nb(A.vent_deg);
  var configured = V.configured || {};
  var showMetric = function (keys) { return !V.adaptive || keys.some(function (key) { return !!configured[key]; }); };`);
    code = code.replace('if (vv !== null) {', "if (vv !== null || vg !== null || (V.dashboard && showMetric(['wind_speed_entity', 'wind_gust_entity']))) {");
    code = code.replace("esc(A.beaufort_tx || 'vent moyen')", "esc(vv === null ? 'vent indisponible' : A.beaufort_tx || 'vent moyen')");
    code = code.replace('if (pj !== null || pt !== null) {', "if (pj !== null || pt !== null || (V.dashboard && showMetric(['daily_rain_entity', 'rain_rate_entity']))) {");
    code = code.replace(": 'pas de pluie en ce moment';", ": pt === null ? 'intensité indisponible' : 'pas de pluie en ce moment';");
    code = code.replace('if (pr !== null) {', "if (pr !== null || (V.dashboard && showMetric(['pressure_entity']))) {");
    code = code.replace("esc(B.tx || 'baromètre')", "esc(pr === null ? 'pression indisponible' : B.tx || 'baromètre')");
    let metric = 0;
    code = code.replaceAll("'<div class=\"me-tut\">'", () => `'<div class="me-tut">' + (V.dashboard ? '<span class="nw-metric-name">${['Vent', 'Pluie', 'Pression'][metric++]}</span>' : '')`);
  }
  // Never borrow ventilation recommendations from a removed integration.
  code = code.replace(/var cre = String\(A\.creneau \|\| ''\);/g, "var cre = '';" );
  out += ` function ${name}() {\n${code}\n }\n`;
}
out += ' const rendered = {' + Object.keys(reference.fields).map(n => `${n}: ${n}()`).join(', ') + '};\n const gauge = rendered.heros.indexOf(\'<div class="me-jauge">\');\n return {...rendered, comfort: gauge < 0 ? "" : rendered.heros.slice(gauge, -6)};\n}\n';
writeFileSync('src/local-renderer.ts', out);
// The template reset white-space on every descendant with an ID selector, overriding the card's own one-line rules.
// :where() keeps the reset as a default (no specificity) so labels, units and numbers can stay on one line.
const css = reference.css.replaceAll('[onclick]', ':is([data-entity], [data-nav])')
  .replace('#container, #container * { white-space: normal; }', ':where(#container, #container *) { white-space: normal; }');
writeFileSync('src/local-styles.ts', '// Generated: exact original CSS apart from event attribute selectors and a zero-specificity white-space reset.\nexport const localStyles = ' + JSON.stringify(css) + ';\n');
if (process.argv[3]) {
  const raw = readFileSync(process.argv[3], 'utf8'), template = parse(raw)[1];
  const E = Object.fromEntries(Object.keys(template.variables.E).map(key => [key,
    key.startsWith('foudre') || key === 'confort' ? '' : key === 'meteo' ? 'weather.test' : `sensor.${key}`]));
  writeFileSync('reference/local-template.json', JSON.stringify({ sha256: createHash('sha256').update(raw).digest('hex'),
    variables: { ...template.variables, E }, attributes: template.sensor[0].attributes }, null, 2) + '\n');
}
