// @ts-nocheck
// Generated by scripts/port-local.mjs from reference/local-renderer.json.
// Original layout and strings retained; globals and inline handlers removed.
export function renderLocal(variables, states, hass) {
 const window = {};
 function heros() {

  var V = variables || {};
  var S = states || {};
  var E = S[V.ent];
  var A = (E && E.attributes) || {};
  var esc = s => String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
window.meGeste = id => id ? ' data-entity="' + esc(id) + '" role="button" tabindex="0"' : '';
var BLEU = 'var(--mush-rgb-blue, 61,155,233)';
  var VERT = 'var(--mush-rgb-green, 76,175,80)';
  var ORANGE = 'var(--mush-rgb-orange, 244,180,86)';
  var ROUGE = 'var(--mush-rgb-red, 244,105,102)';
  var GRIS = 'var(--mush-rgb-grey, 150,150,150)';
  var NIV = {optimise: BLEU, benefice: VERT, action: ORANGE,
             urgent: ROUGE, neutre: GRIS};
  window.meCond = {
    'sunny':          {i: 'mdi:weather-sunny',          n: 'Grand soleil'},
    'clear-night':    {i: 'mdi:weather-night',          n: 'Nuit claire'},
    'partlycloudy':   {i: 'mdi:weather-partly-cloudy',  n: 'Éclaircies'},
    'cloudy':         {i: 'mdi:weather-cloudy',         n: 'Ciel couvert'},
    'fog':            {i: 'mdi:weather-fog',            n: 'Brouillard'},
    'rainy':          {i: 'mdi:weather-rainy',          n: 'Pluvieux'},
    'pouring':        {i: 'mdi:weather-pouring',        n: 'Fortes pluies'},
    'lightning':      {i: 'mdi:weather-lightning',      n: 'Orageux'},
    'lightning-rainy':{i: 'mdi:weather-lightning-rainy',n: 'Orages'},
    'hail':           {i: 'mdi:weather-hail',           n: 'Grêle'},
    'snowy':          {i: 'mdi:weather-snowy',          n: 'Neige'},
    'snowy-rainy':    {i: 'mdi:weather-snowy-rainy',    n: 'Pluie et neige'},
    'windy':          {i: 'mdi:weather-windy',          n: 'Venteux'},
    'windy-variant':  {i: 'mdi:weather-windy-variant',  n: 'Venteux'},
    'exceptional':    {i: 'mdi:alert-outline',          n: 'Exceptionnel'}
  };
  window.meNb = function (x) {
    if (x === null || x === undefined || x === '') return null;
    var v = parseFloat(x);
    return (isFinite(v) && v > -900) ? v : null;
  };
  window.meFr = function (v, d) {
    if (v === null || v === undefined) return '—';
    return v.toFixed(d === undefined ? 1 : d).replace('.', ',');
  };
  var nb = window.meNb, fr = window.meFr;
  var dispo = !!E && E.state !== 'unavailable' && E.state !== 'unknown';
  var SRC = (A.sources && typeof A.sources === 'object') ? A.sources : {};
  window.meSrc = SRC;
  var niveau = String(A.niveau || 'optimise');
  var vc = V.brief ? V.brief.rgb : NIV[niveau] || BLEU;
  var res = nb(A.ressenti);
  var tex = nb(A.t_ext);
  var hum = nb(A.humidex);
  var ev = nb(A.effet_vent);
  var es = nb(A.effet_soleil);
  var ep = nb(A.effet_pluie);
  var en = nb(A.effet_nuit);
  var meta = window.meCond[String(A.condition || '')] || null;
  var titre = String(A.titre || (meta ? meta.n : 'Dehors'));
  var ico = V.brief ? V.brief.icon : meta ? meta.i : 'mdi:thermometer';
  var jmin = nb(V.jauge_min); if (jmin === null) jmin = -5;
  var jmax = nb(V.jauge_max); if (jmax === null) jmax = 45;
  var pos = function (t) {
    if (t === null) return null;
    var p = (t - jmin) / (jmax - jmin) * 100;
    return Math.max(0.5, Math.min(99.5, p));
  };
  var pRes = pos(res), pTex = pos(tex);
  var deco = '';
  var pastille = function (icone, etiq, val, couleur, tip, src) {
    return '<span class="me-d" style="--dc: ' + couleur + ';"'
         +   (tip ? ' title="' + esc(tip) + '"' : '')
         +   window.meGeste(src) + '>'
         +   '<ha-icon icon="' + icone + '"></ha-icon>'
         +   '<b>' + esc(val) + '</b>'
         +   '<i>' + esc(etiq) + '</i>'
         + '</span>';
  };
  if (hum !== null) {
    deco += pastille('mdi:water-percent', V.dashboard ? 'base humidex' : 'humidex', fr(hum, 1) + '°',
                     'var(--mush-rgb-cyan, 77,182,172)',
                     A.perception || '', SRC.humidex);
  }
  if (ev !== null && Math.abs(ev) >= 0.1) {
    deco += pastille('mdi:weather-windy', 'vent',
                     (ev > 0 ? '+' : '−') + fr(Math.abs(ev), 1) + '°', BLEU,
                     '', SRC.vent);
  }
  if (es !== null && Math.abs(es) >= 0.1) {
    deco += pastille('mdi:white-balance-sunny', 'soleil',
                     '+' + fr(es, 1) + '°',
                     'var(--mush-rgb-amber, 255,193,7)', '', SRC.solaire);
  }
  if (ep !== null && Math.abs(ep) >= 0.1) {
    deco += pastille('mdi:weather-pouring', 'pluie',
                     '−' + fr(Math.abs(ep), 1) + '°',
                     'var(--mush-rgb-blue, 33,150,243)',
                     'peau mouillée : le vent emporte bien plus vite',
                     SRC.pluie_taux);
  }
  if (en !== null && Math.abs(en) >= 0.1) {
    deco += pastille('mdi:weather-night', 'ciel clair',
                     '−' + fr(Math.abs(en), 1) + '°',
                     'var(--mush-rgb-indigo, 63,81,181)',
                     'ciel dégagé : le corps rayonne vers le vide',
                     SRC.meteo);
  }
  var ALERTE = {orage: 'ORAGE', averse: 'AVERSE',
                rafales: 'RAFALES', canicule: 'CANICULE', gel: 'GEL',
                chaleur: 'CHALEUR', froid: 'FROID', uv: 'UV'};
  var badge = V.brief ? V.brief.label : ALERTE[String(A.alerte || '')] || '';
  var mesure = !V.brief && String(A.cond_source || '') === 'station';
  var mprev = window.meCond[String(A.condition_prev || '')] || null;
  var tipSrc = 'constaté par la station, au-dessus de la maison'
             + (mprev ? ' — Météo-France annonce « ' + mprev.n + ' »' : '');
  var sous = String(A.sous_titre || '');
  if (V.lieu && !V.brief) sous = sous ? (sous + ' · ' + V.lieu) : String(V.lieu);
  if (!dispo) {
    return '<div class="me-hero" style="--vc: ' + GRIS + ';">'
         +   '<div class="me-bulle"><div class="me-rond">'
         +     '<ha-icon icon="mdi:weather-cloudy-alert"></ha-icon>'
         +   '</div></div>'
         +   '<div class="me-htx"><div class="me-t">Météo indisponible</div>'
         +     '<div class="me-p">Le capteur ne répond pas — ni humidex, '
         +     'ni température extérieure.</div></div>'
         + '</div>';
  }
  var h = '<div class="me-hero me-hero--vif" style="--vc: ' + vc + ';">';
  h +=   '<div class="me-htop">';
  h +=     '<div class="me-bulle">'
    +        '<div class="me-halo"></div>'
    +        '<div class="me-rond"><ha-icon icon="' + ico + '"></ha-icon></div>'
    +      '</div>';
  h +=     '<div class="me-htx">';
  h +=       '<div class="me-t">' + esc(titre)
    +          (badge ? '<span class="me-badge">' + esc(badge) + '</span>' : '')
    +          (mesure ? '<span class="me-src" title="' + esc(tipSrc)
                          + '">mesuré ici</span>' : '')
    +        '</div>';
  h +=       '<div class="me-p">' + esc(sous) + '</div>';
  h +=     '</div>';
  var duo = (tex !== null && res !== null && Math.abs(res - tex) >= 0.35)
    ? '<span class="me-hr">' + fr(tex, 1) + '° au thermomètre</span>' : '';
  h +=     '<div class="me-hval"' + window.meGeste(SRC.t_ext) + '>'
    +        '<span class="me-hv">' + fr(res, 1) + '<i>°</i></span>'
    +        '<span class="me-hl">ressenti</span>'
    +        duo
    +      '</div>';
  h +=   '</div>';
  if (pRes !== null) {
    h += '<div class="me-jauge">';
    h +=   '<div class="me-rail">';
    if (pTex !== null) {
      h += '<span class="me-tick" style="left: ' + pTex.toFixed(1) + '%;"'
        +  ' title="' + fr(tex, 1) + ' °C au thermomètre"></span>';
    }
    if (V.dashboard) h += '<strong class="nw-feels-value" style="left:clamp(42px,' + pRes.toFixed(1) + '%,calc(100% - 42px))">' + fr(res, 1) + '<small>°C</small></strong>';
  h +=     '<span class="me-cur" style="left: ' + pRes.toFixed(1) + '%;">'
      +        '<i></i></span>';
    h +=   '</div>';
    h +=   '<div class="me-jl">'
      +      '<span>' + fr(jmin, 0) + '°</span>'
      +      '<span class="me-jph">' + esc(A.phrase_ressenti || '') + '</span>'
      +      '<span>' + fr(jmax, 0) + '°</span>'
      +    '</div>';
    h += '</div>';
  }
  if (deco) h += '<div class="me-decos">' + deco + '</div>';
  h += '</div>';
  return h;

 }
 function essentiels() {

  var V = variables || {};
  if ((V.mode || 'complet') !== 'accueil') return '';
  var S = states || {};
  var E = S[V.ent];
  var A = (E && E.attributes) || {};
  if (!E || E.state === 'unavailable' || E.state === 'unknown') return '';
  var nb = window.meNb, fr = window.meFr;
  if (!nb || !fr) return '';
  var esc = function (s) {
    return String(s == null ? '' : s)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  };
  var BLEU = 'var(--mush-rgb-blue, 61,155,233)';
  var VERT = 'var(--mush-rgb-green, 76,175,80)';
  var ORANGE = 'var(--mush-rgb-orange, 244,180,86)';
  var ROUGE = 'var(--mush-rgb-red, 244,105,102)';
  var GRIS = 'var(--mush-rgb-grey, 150,150,150)';
  var CYAN = 'var(--mush-rgb-cyan, 77,182,172)';
  var NIV = {optimise: BLEU, benefice: VERT, action: ORANGE,
             urgent: ROUGE, neutre: GRIS};
  var out = '';
  var puce = function (ico, val, lbl, coul) {
    return '<span class="me-pa" style="--pc: ' + coul + ';">'
         +   '<ha-icon icon="' + ico + '"></ha-icon>'
         +   '<b>' + val + '</b><i>' + esc(lbl) + '</i>'
         + '</span>';
  };
  var vv = nb(A.vent), rose = String(A.vent_rose || '');
  if (vv !== null) {
    out += puce('mdi:weather-windy', esc(fr(vv, 0)) + '<small>km/h</small>',
                rose ? 'secteur ' + esc(rose) : 'vent', GRIS);
  }
  var pj = nb(A.pluie_jour);
  if (pj !== null) {
    out += puce('mdi:water-outline', esc(fr(pj, 1)) + '<small>mm</small>',
                'depuis minuit', pj > 0 ? CYAN : GRIS);
  }
  var uv = nb(A.uv);
  if (uv !== null && uv >= 3) {
    out += puce('mdi:sun-wireless-outline', esc(fr(uv, 0)),
                'UV ' + esc(A.uv_tx || ''),
                uv >= 8 ? ROUGE : uv >= 6 ? ORANGE
                        : 'var(--mush-rgb-amber, 255,193,7)');
  }
  var fin = '';
  var pd = nb(A.pluie_dans), pmm = nb(A.pluie_mm);
  if (pd !== null && pd >= 0) {
    fin += puce('mdi:weather-pouring',
                pd === 0 ? 'pluie dans l’heure' : 'pluie dans ' + pd + ' h',
                pmm ? esc(fr(pmm, 1)) + ' mm' : '', CYAN);
  }
  var baro = (A.baro && typeof A.baro === 'object') ? A.baro : {};
  if (baro.tx) {
    fin += puce('mdi:gauge', esc(baro.tx), 'baromètre',
                baro.s === 'baisse' ? ORANGE : GRIS);
  }
  var cre = '';
  if (cre) fin += puce('mdi:window-open-variant', esc(cre), '', VERT);
  if (out && fin) out += '<span class="me-pas-sep"></span>';
  out += fin;
  return out ? '<div class="me-pas me-pas--ess">' + out + '</div>' : '';

 }
 function sect1() {

  if (((variables || {}).mode || 'complet') === 'accueil') return '';
  var V = variables || {};
  var e = (states || {})[V.ent];
  if (!e || e.state === 'unavailable' || e.state === 'unknown') return '';
  return '<div class="me-sect"><b>Aujourd’hui</b>'
       + '<i>mesuré au-dessus de la maison</i></div>';

 }
 function sect2() {

  if (((variables || {}).mode || 'complet') === 'accueil') return '';
  var V = variables || {};
  var p = V.ent_prev ? (states || {})[V.ent_prev] : null;
  var a = (p && p.attributes) || {};
  var h = a.heures, j = a.jours;
  if (!(h && h.length >= 3) && !(j && j.length)) return '';
  var nom = V.source_prev || 'prévisions';
  return '<div class="me-sect"><b>Ce qui arrive</b>'
       + '<i>' + String(nom).replace(/&/g, '&amp;').replace(/</g, '&lt;')
       + '</i></div>';

 }
 function sect3() {

  if (((variables || {}).mode || 'complet') === 'accueil') return '';
  var V = variables || {};
  var a = ((states || {})[V.ent] || {}).attributes || {};
  var n = window.meNb || function (x) {
    var v = parseFloat(x); return (isFinite(v) && v > -900) ? v : null; };
  if (n(a.pluie_semaine) === null && n(a.pluie_mois) === null
      && n(a.rafale_max_jour) === null) return '';
  return '<div class="me-sect"><b>Ce qui s’est passé</b>'
       + '<i>compteurs cumulés de la station</i></div>';

 }
 function bilan() {

  if (((variables || {}).mode || 'complet') === 'accueil') return '';
  var V = variables || {};
  var S = states || {};
  var A = ((S[V.ent] || {}).attributes) || {};
  var esc = function (s) {
    return String(s == null ? '' : s)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  };
  var nb = window.meNb, fr = window.meFr;
  if (!nb || !fr) return '';
  var SRC = (A.sources && typeof A.sources === 'object') ? A.sources : {};
  var CYAN = 'var(--mush-rgb-cyan, 77,182,172)';
  var BLEU = 'var(--mush-rgb-blue, 61,155,233)';
  var GRIS = 'var(--mush-rgb-grey, 150,150,150)';
  var ligne = function (nom, pct, val, unite, src, faible) {
    return '<div class="me-blr' + (faible ? ' me-blr--faible' : '') + '"'
         +   window.meGeste(src) + '>'
         +   '<span class="me-bln">' + esc(nom) + '</span>'
         +   '<span class="me-blb">'
         +     (pct === null ? ''
                : '<i style="width:' + Math.max(1.5, pct).toFixed(1)
                  + '%;"></i>')
         +   '</span>'
         +   '<span class="me-blv">' + esc(val)
         +     (unite ? '<em>' + esc(unite) + '</em>' : '') + '</span>'
         + '</div>';
  };
  var blocs = '';
  var p24 = nb(A.pluie_24h), pse = nb(A.pluie_semaine),
      pmo = nb(A.pluie_mois), pan = nb(A.pluie_an),
      pjo = nb(A.pluie_jour);
  if (pse !== null || pmo !== null) {
    var ech = Math.max(5, p24 || 0, pse || 0, pmo || 0);
    var pc = function (v) { return v === null ? null : v / ech * 100; };
    var l = '';
    if (p24 !== null) l += ligne('24 h', pc(p24), fr(p24, 1), 'mm', SRC.pluie_24h);
    else if (pjo !== null) l += ligne('aujourd’hui', pc(pjo), fr(pjo, 1), 'mm', SRC.pluie_jour);
    if (pse !== null) l += ligne('Cette semaine', pc(pse), fr(pse, 1), 'mm', SRC.pluie_semaine);
    if (pmo !== null) l += ligne('Ce mois', pc(pmo), fr(pmo, 1), 'mm', SRC.pluie_mois);
    if (pan !== null) l += ligne('année', null, fr(pan, 1), 'mm', SRC.pluie_an, true);
    var recit = String(A.pluie_recit || '');
    blocs += '<div class="me-bl" style="--bc: ' + CYAN + ';">'
          +    '<div class="me-blt"><ha-icon icon="mdi:weather-pouring">'
          +      '</ha-icon><span>Pluie</span></div>'
          +    l
          +    (recit ? '<div class="me-blp">' + esc(recit) + '</div>' : '')
          +  '</div>';
  }
  var rmax = nb(A.rafale_max_jour), raf = nb(A.rafales), vv = nb(A.vent);
  var T = (A.vent_t && typeof A.vent_t === 'object') ? A.vent_t : {};
  var vd = nb(T.d), vf = nb(T.f);
  if (rmax !== null || vd !== null) {
    var lv = '';
    if (rmax !== null) {
      lv += ligne('rafale max du jour', 100, fr(rmax, 0), 'km/h',
                  SRC.rafale_max_jour);
      if (raf !== null) {
        lv += ligne('en ce moment', rmax > 0 ? (raf / rmax * 100) : 0,
                    fr(raf, 0), 'km/h', SRC.rafales);
      }
    } else if (raf !== null) {
      lv += ligne('rafales', null, fr(raf, 0), 'km/h', SRC.rafales);
    }
    var tv = '';
    if (vd !== null && T.tx) {
      tv = String(T.tx) + ' · ' + (vd > 0 ? '+' : '−')
         + fr(Math.abs(vd), 0) + ' km/h'
         + (vf !== null && vf < 50 ? ' sur ' + fr(vf, 0) + ' min' : ' sur 1 h');
    } else {
      tv = 'tendance en cours de mesure';
    }
    var tc = (T.s === 'hausse') ? BLEU : GRIS;
    blocs += '<div class="me-bl" style="--bc: ' + tc + ';">'
          +    '<div class="me-blt"><ha-icon icon="mdi:weather-windy">'
          +      '</ha-icon><span>Vent</span></div>'
          +    lv
          +    '<div class="me-blp">' + esc(tv) + '</div>'
          +  '</div>';
  }
  return blocs ? '<div class="me-bilan">' + blocs + '</div>' : '';

 }
 function courbe() {

  if (((variables || {}).mode || 'complet') === 'accueil') return '';
  var V = variables || {};
  var S = states || {};
  var E = S[V.ent];
  var A = (E && E.attributes) || {};
  var esc = function (s) {
    return String(s == null ? '' : s)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  };
  var nb = window.meNb, fr = window.meFr;
  if (!nb || !fr || !window.meCond) return '';
  var PV = V.ent_prev ? S[V.ent_prev] : null;
  var pts = (PV && PV.attributes) ? PV.attributes.heures : null;
  if (!pts || !pts.length || pts.length < 3) return '';
  var PX = 2;    
  var PT = 22;   
  var PB = 88;   
  var n = pts.length;
  var X = function (i) { return PX + i * (100 - 2 * PX) / (n - 1); };
  var ts = pts.map(function (p) { return nb(p.t); })
              .filter(function (v) { return v !== null; });
  if (ts.length < 3) return '';
  var lo = Math.min.apply(null, ts), hi = Math.max.apply(null, ts);
  if (hi - lo < 3) { var c = (hi + lo) / 2; lo = c - 1.5; hi = c + 1.5; }
  lo -= (hi - lo) * 0.12; hi += (hi - lo) * 0.10;
  var Y = function (t) { return PT + (1 - (t - lo) / (hi - lo)) * (PB - PT); };
  var lev = nb(A.lever), cou = nb(A.coucher);
  if (lev === null) lev = 6.5;
  if (cou === null) cou = 21;
  var nuit = function (h) { return h < lev || h >= cou; };
  var demi = (100 - 2 * PX) / (n - 1) / 2;
  var bandes = '', deb = -1;
  for (var i = 0; i <= n; i++) {
    var est = (i < n) && nuit(nb(pts[i].h));
    if (est && deb < 0) deb = i;
    if (!est && deb >= 0) {
      var x1 = Math.max(0, X(deb) - demi);
      var x2 = Math.min(100, X(i - 1) + demi);
      bandes += '<i class="me-nuit" style="left:' + x1.toFixed(2)
             +  '%;width:' + (x2 - x1).toFixed(2)
             +  '%;height:' + PB + '%;"></i>';
      deb = -1;
    }
  }
  var ps = pts.map(function (p) { return nb(p.p) || 0; });
  var pmax = Math.max.apply(null, ps);
  var barres = '';
  if (pmax >= 0.1) {
    var pech = Math.max(1.2, Math.min(pmax, 4));
    var bw = Math.min(2.6, demi * 0.9);
    for (var k = 0; k < n; k++) {
      if (ps[k] < 0.1) continue;
      var bh = Math.max(4, Math.min(1, ps[k] / pech) * (PB - PT) * 0.44);
      barres += '<i class="me-bar" style="left:' + (X(k) - bw / 2).toFixed(2)
             +  '%;width:' + bw.toFixed(2)
             +  '%;top:' + (PB - bh).toFixed(2)
             +  '%;height:' + bh.toFixed(2) + '%;"></i>';
    }
  }
  var Q = [];
  for (var j = 0; j < n; j++) {
    var t = nb(pts[j].t);
    if (t === null) continue;
    Q.push({x: X(j), y: Y(t)});
  }
  var d = 'M' + Q[0].x.toFixed(2) + ' ' + Q[0].y.toFixed(2);
  for (var m = 0; m < Q.length - 1; m++) {
    var p0 = Q[m - 1] || Q[m], p1 = Q[m], p2 = Q[m + 1],
        p3 = Q[m + 2] || Q[m + 1];
    d += 'C' + (p1.x + (p2.x - p0.x) / 6).toFixed(2) + ' '
             + (p1.y + (p2.y - p0.y) / 6).toFixed(2) + ','
             + (p2.x - (p3.x - p1.x) / 6).toFixed(2) + ' '
             + (p2.y - (p3.y - p1.y) / 6).toFixed(2) + ','
             + p2.x.toFixed(2) + ' ' + p2.y.toFixed(2);
  }
  var aire = d + 'L' + Q[Q.length - 1].x.toFixed(2) + ' ' + PB
           + 'L' + Q[0].x.toFixed(2) + ' ' + PB + 'Z';
  var iMin = 0, iMax = 0;
  for (var q = 0; q < n; q++) {
    var tq = nb(pts[q].t);
    if (tq === null) continue;
    if (tq < nb(pts[iMin].t)) iMin = q;
    if (tq > nb(pts[iMax].t)) iMax = q;
  }
  var reperes = '';
  var repere = function (idx, haut) {
    var tv = nb(pts[idx].t);
    if (tv === null) return;
    var x = X(idx), y = Y(tv);
    var tx = (x < 9) ? '0' : (x > 91) ? '-100%' : '-50%';
    var ty = haut ? 'calc(-100% - 9px)' : '9px';
    reperes += '<i class="me-pt" style="left:' + x.toFixed(2)
            +  '%;top:' + y.toFixed(2) + '%;"></i>'
            +  '<span class="me-lbl" style="left:' + x.toFixed(2)
            +  '%;top:' + y.toFixed(2) + '%;transform:translate('
            +  tx + ',' + ty + ');">' + esc(fr(tv, 0)) + '°</span>';
  };
  repere(iMax, true);
  repere(iMin, false);
  var axes = '';
  for (var a = 0; a < n; a++) {
    var hh = nb(pts[a].h);
    if (hh === null || hh % 3 !== 0) continue;
    var xa = X(a);
    var tax = (xa < 6) ? '0' : (xa > 94) ? '-100%' : '-50%';
    axes += '<span style="left:' + xa.toFixed(2)
         +  '%;transform:translateX(' + tax + ');">' + hh + ' h</span>';
  }
  var maint = '<i class="me-now" style="left:' + X(0).toFixed(2)
            + '%;height:' + PB + '%;"></i>'
            + '<span class="me-nowl" style="left:' + X(0).toFixed(2)
            + '%;">MAINTENANT</span>';
  var demain = '';
  for (var b = 1; b < n; b++) {
    if (nb(pts[b].j) > nb(pts[b - 1].j)) {
      var xd = (X(b) + X(b - 1)) / 2;
      demain = '<i class="me-jour" style="left:' + xd.toFixed(2)
             + '%;height:' + PB + '%;"></i>'
             + '<span class="me-jourl" style="left:clamp(0px,' + xd.toFixed(2)
             + '%,calc(100% - 48px));">DEMAIN</span>';
      break;
    }
  }
  var sv = '<svg class="me-svg" viewBox="0 0 100 100" '
         + 'preserveAspectRatio="none" aria-hidden="true">'
         + '<defs><linearGradient id="meAire" x1="0" y1="0" x2="0" y2="1">'
         +   '<stop offset="0%" class="me-g1"/>'
         +   '<stop offset="100%" class="me-g2"/>'
         + '</linearGradient></defs>'
         + '<path d="' + aire + '" class="me-aire"/>'
         + '<path d="' + d + '" class="me-ligne" '
         +   'vector-effect="non-scaling-stroke"/>'
         + '</svg>';
  var pied = '';
  var ligne = function (ico, txt, cls) {
    return '<span class="me-pf' + (cls || '') + '">'
         + '<ha-icon icon="' + ico + '"></ha-icon>'
         + '<span>' + esc(txt) + '</span></span>';
  };
  var pd = nb(A.pluie_dans), pmm = nb(A.pluie_mm);
  if (pd !== null && pd >= 0) {
    pied += ligne('mdi:weather-pouring',
                  (pd === 0 ? 'pluie dans l’heure' : 'pluie dans ' + pd + ' h')
                  + (pmm ? ' · ' + fr(pmm, 1) + ' mm' : ''), ' me-pf--pluie');
  } else if (pd === -1) {
    pied += ligne('mdi:weather-sunny', 'pas de pluie sur les 18 h', '');
  }
  var cre = '';
  if (cre) pied += ligne('mdi:window-open-variant', cre, ' me-pf--cre');
  if (pied) pied = '<div class="me-pied">' + pied + '</div>';
  var src = (window.meSrc || {}).meteo || V.ent;
  return '<div class="me-courbe"' + window.meGeste(src) + '>'
       + '<div class="me-ttl">Les 18 heures qui viennent'
       + (pmax >= 0.1 ? '<i>· pluie en barres</i>' : '') + '</div>'
       + '<div class="me-graph" role="img" aria-label="Températures des '
       + '18 prochaines heures">'
       +   bandes + sv + barres + maint + demain + reperes
       + '</div>'
       + '<div class="me-axe">' + axes + '</div>'
       + pied + '</div>';

 }
 function jours() {

  if (((variables || {}).mode || 'complet') === 'accueil') return '';
  var V = variables || {};
  var S = states || {};
  var A = ((S[V.ent] || {}).attributes) || {};
  var esc = function (s) {
    return String(s == null ? '' : s)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  };
  var nb = window.meNb, fr = window.meFr;
  if (!nb || !fr || !window.meCond) return '';
  var PV = V.ent_prev ? S[V.ent_prev] : null;
  var js = (PV && PV.attributes) ? PV.attributes.jours : null;
  if (!js || !js.length) return '';
  var maxj = nb(V.jours_max); if (maxj === null) maxj = 7;
  js = js.slice(0, maxj);
  var lo = null, hi = null;
  js.forEach(function (j) {
    var t = nb(j.t), m = nb(j.m);
    [t, m].forEach(function (v) {
      if (v === null) return;
      if (lo === null || v < lo) lo = v;
      if (hi === null || v > hi) hi = v;
    });
  });
  if (lo === null || hi === null) return '';
  if (hi - lo < 4) { var c = (hi + lo) / 2; lo = c - 2; hi = c + 2; }
  lo -= 0.5; hi += 0.5;
  var pc = function (v) { return (v - lo) / (hi - lo) * 100; };
  var pmax = 0;
  js.forEach(function (j) { pmax = Math.max(pmax, nb(j.p) || 0); });
  var lignes = '';
  js.forEach(function (j, idx) {
    var meta = window.meCond[String(j.c || '')] || null;
    var t = nb(j.t), m = nb(j.m), p = nb(j.p) || 0;
    var seg;
    if (t !== null && m !== null) {
      var a = pc(m), b = pc(t);
      seg = '<span class="me-jseg" style="left: ' + a.toFixed(1)
          + '%; width: ' + Math.max(2, b - a).toFixed(1) + '%;"></span>';
    } else if (t !== null) {
      seg = '<span class="me-jseg me-jseg--pt" style="left: '
          + Math.max(0, pc(t) - 1).toFixed(1) + '%; width: 2%;"></span>';
    } else {
      seg = '';
    }
    var nom = (nb(j.e) === 0) ? 'AUJ.' : String(j.n || '');
    lignes += '<div class="me-j' + (nb(j.e) === 0 ? ' me-j--auj' : '') + '">'
           +    '<span class="me-jn">' + esc(nom) + '</span>'
           +    '<span class="me-ji">'
           +      (meta ? '<ha-icon icon="' + meta.i + '"></ha-icon>' : '')
           +    '</span>'
           +    '<span class="me-jmin">'
           +      (m !== null ? esc(fr(m, 0)) + '°' : '') + '</span>'
           +    '<span class="me-jbar">' + seg + '</span>'
           +    '<span class="me-jmax">'
           +      (t !== null ? esc(fr(t, 0)) + '°' : '—') + '</span>'
           +    '<span class="me-jp">'
           +      (p >= 0.1 ? esc(fr(p, 1)) + '<i>mm</i>' : '') + '</span>'
           +  '</div>';
  });
  var src = (window.meSrc || {}).meteo || V.ent;
  return '<div class="me-jours"' + window.meGeste(src) + '>'
       + '<div class="me-ttl">La semaine'
       + (pmax >= 0.1 ? '<i>· cumuls attendus</i>' : '') + '</div>'
       + (V.dashboard ? '<div class="me-j nw-week-labels" role="group" aria-label="Colonnes : température minimale et maximale en degrés Celsius, pluie en millimètres"><span class="me-jn"></span><span class="me-ji"></span><span class="me-jmin">Min<small>°C</small></span><span class="me-jbar"></span><span class="me-jmax">Max<small>°C</small></span><span class="me-jp">Pluie<small>mm</small></span></div>' : '') + lignes + '</div>';

 }
 function tuiles() {

  if (((variables || {}).mode || 'complet') === 'accueil') return '';
  var V = variables || {};
  var S = states || {};
  var A = ((S[V.ent] || {}).attributes) || {};
  var esc = function (s) {
    return String(s == null ? '' : s)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  };
  var nb = window.meNb, fr = window.meFr;
  if (!nb || !fr) return '';
  var SRC = (A.sources && typeof A.sources === 'object') ? A.sources : {};
  var BLEU = 'var(--mush-rgb-blue, 61,155,233)';
  var CYAN = 'var(--mush-rgb-cyan, 77,182,172)';
  var ORANGE = 'var(--mush-rgb-orange, 244,180,86)';
  var GRIS = 'var(--mush-rgb-grey, 150,150,150)';
  var out = V.dashboard ? '<div class="me-tu" style="--tc:var(--mush-rgb-blue,61,155,233)"' + window.meGeste(SRC.t_ext) + '><div class="me-tuic"><ha-icon icon="mdi:thermometer"></ha-icon></div><div class="me-tut"><span class="nw-metric-name">Température</span><span class="me-tuv">' + esc(fr(nb(A.t_ext), 1)) + '<i>°C</i></span><span class="me-tul">' + (nb(A.ressenti) === null ? 'ressenti indisponible' : 'ressenti ' + esc(fr(nb(A.ressenti), 1)) + ' °C') + '</span><span class="me-tus">' + (nb(A.t_ext) === null ? 'température indisponible' : esc(A.perception || (V.adaptive && !V.configured?.temperature_entity ? 'température du bulletin' : 'au thermomètre'))) + '</span></div></div>' : '';
  var vv = nb(A.vent), vg = nb(A.rafales), vd = nb(A.vent_deg);
  var configured = V.configured || {};
  var showMetric = function (keys) { return !V.adaptive || keys.some(function (key) { return !!configured[key]; }); };
  var rose = String(A.vent_secteur || A.vent_rose || '');
  if (vv !== null || vg !== null || (V.dashboard && showMetric(['wind_speed_entity', 'wind_gust_entity']))) {
    var bf = nb(A.beaufort);
    var wc = (vg !== null && vg >= 60) ? ORANGE
           : (vg !== null && vg >= 40) ? BLEU : GRIS;
    var aig = '';
    if (vd !== null && vd >= 0) {
      aig = '<g class="me-aig" style="transform: rotate(' + vd.toFixed(0)
          + 'deg);">'
          +   '<path d="M20 6 L24 21 L20 18.5 L16 21 Z" class="me-aigp"/>'
          + '</g>';
    }
    var cadran = '<svg class="me-rose" viewBox="0 0 40 40" aria-hidden="true">'
      + '<circle cx="20" cy="20" r="17.2" class="me-rc"/>'
      + '<text x="20" y="7.4" text-anchor="middle" class="me-rn">N</text>'
      + '<circle cx="20" cy="20" r="1.7" class="me-rd"/>'
      + aig + '</svg>';
    var dtl = (vg !== null ? 'rafales ' + fr(vg, 0) : '')
            + (bf !== null && bf >= 0
                 ? (vg !== null ? ' · ' : '') + 'force ' + fr(bf, 0) : '');
    var titre_v = (A.vent_nom ? 'vent venant ' + A.vent_nom : '')
                + (A.beaufort_tx
                     ? (A.vent_nom ? ' · ' : '') + A.beaufort_tx : '');
    out += '<div class="me-tu" style="--tc: ' + wc + ';" title="'
         +   esc(titre_v) + '"' + window.meGeste(SRC.vent) + '>'
         +   cadran
         +   '<div class="me-tut">' + (V.dashboard ? '<span class="nw-metric-name">Vent</span>' : '')
         +     '<span class="me-tuv">' + esc(fr(vv, 0)) + '<i>km/h</i></span>'
         +     '<span class="me-tul">'
         +       (rose ? 'secteur ' + esc(rose)
                        : esc(vv === null ? 'vent indisponible' : A.beaufort_tx || 'vent moyen')) + '</span>'
         +     '<span class="me-tus">' + esc(dtl) + '</span>'
         +   '</div>'
         + '</div>';
  }
  var pj = nb(A.pluie_jour), pt = nb(A.pluie_taux);
  var pdans = nb(A.pluie_dans), pmm = nb(A.pluie_mm);
  if (pj !== null || pt !== null || (V.dashboard && showMetric(['daily_rain_entity', 'rain_rate_entity']))) {
    var pleut = (pt !== null && pt > 0.05);
    var pc2 = (pleut || (pdans !== null && pdans >= 0)) ? CYAN : GRIS;
    var gouttes = '';
    if (pleut) {
      for (var g = 0; g < 3; g++) {
        gouttes += '<i class="me-gt" style="left: ' + (10 + g * 11)
                +  'px; animation-delay: ' + (g * 0.33).toFixed(2) + 's;"></i>';
      }
    }
    var sousp = pleut ? (fr(pt, 1) + ' mm/h en ce moment')
                      : pt === null ? 'intensité indisponible' : 'pas de pluie en ce moment';
    out += '<div class="me-tu" style="--tc: ' + pc2 + ';"'
         +   window.meGeste(SRC.pluie_jour) + '>'
         +   '<div class="me-tuic' + (pleut ? ' me-tuic--pluie' : '') + '">'
         +     '<ha-icon icon="' + (pleut ? 'mdi:weather-pouring'
                                          : 'mdi:water-outline') + '"></ha-icon>'
         +     gouttes
         +   '</div>'
         +   '<div class="me-tut">' + (V.dashboard ? '<span class="nw-metric-name">Pluie</span>' : '')
         +     '<span class="me-tuv">' + esc(fr(pj, 1)) + '<i>mm</i></span>'
         +     '<span class="me-tul">depuis minuit</span>'
         +     '<span class="me-tus">' + esc(sousp) + '</span>'
         +   '</div>'
         + '</div>';
  }
  var B = (A.baro && typeof A.baro === 'object') ? A.baro : {};
  var pr = nb(A.pression), bd = nb(B.d);
  var bs = String(B.s || ''), bfen = nb(B.f);
  if (pr !== null || (V.dashboard && showMetric(['pressure_entity']))) {
    var ang = 0, bc = GRIS;
    if (bs === 'hausse') { ang = -42; bc = BLEU; }
    else if (bs === 'baisse') { ang = 42; bc = ORANGE; }
    var det;
    if (bd === null) {
      det = 'tendance en cours de mesure';
    } else {
      var fen = (bfen !== null && bfen < 150)
              ? 'sur ' + fr(bfen, 0) + ' min' : 'sur 3 h';
      det = (bd > 0 ? '+' : '−') + fr(Math.abs(bd), 1) + ' hPa ' + fen;
    }
    out += '<div class="me-tu" style="--tc: ' + bc + ';"'
         +   window.meGeste(SRC.pression) + '>'
         +   '<div class="me-tuic">'
         +     '<ha-icon icon="mdi:arrow-up-thick" class="me-fle" style="'
         +       'transform: rotate(' + (ang + 90) + 'deg);"></ha-icon>'
         +   '</div>'
         +   '<div class="me-tut">' + (V.dashboard ? '<span class="nw-metric-name">Pression</span>' : '')
         +     '<span class="me-tuv">' + esc(fr(pr, 0)) + '<i>hPa</i></span>'
         +     '<span class="me-tul">' + esc(pr === null ? 'pression indisponible' : B.tx || 'baromètre') + '</span>'
         +     '<span class="me-tus">' + esc(det) + '</span>'
         +   '</div>'
         + '</div>';
  }
  return out ? '<div class="me-tuiles">' + out + '</div>' : '';

 }
 function pastilles() {

  if (((variables || {}).mode || 'complet') === 'accueil') return '';
  var V = variables || {};
  var S = states || {};
  var A = ((S[V.ent] || {}).attributes) || {};
  var esc = function (s) {
    return String(s == null ? '' : s)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  };
  var nb = window.meNb, fr = window.meFr;
  if (!nb || !fr) return '';
  var SRC = (A.sources && typeof A.sources === 'object') ? A.sources : {};
  var BLEU = 'var(--mush-rgb-blue, 61,155,233)';
  var VERT = 'var(--mush-rgb-green, 76,175,80)';
  var ORANGE = 'var(--mush-rgb-orange, 244,180,86)';
  var ROUGE = 'var(--mush-rgb-red, 244,105,102)';
  var GRIS = 'var(--mush-rgb-grey, 150,150,150)';
  var AMBRE = 'var(--mush-rgb-amber, 255,193,7)';
  var CYAN = 'var(--mush-rgb-cyan, 77,182,172)';
  var NIV = {optimise: BLEU, benefice: VERT, action: ORANGE,
             urgent: ROUGE, neutre: GRIS};
  var out = '';
  var pas = function (ico, val, lbl, coul, geste) {
    return '<span class="me-pa" style="--pc: ' + coul + ';"' + (geste || '') + '>'
         +   '<ha-icon icon="' + ico + '"></ha-icon>'
         +   '<b>' + val + '</b><i>' + esc(lbl) + '</i>'
         + '</span>';
  };
  var uv = nb(A.uv);
  if (uv !== null) {
    var uc = uv >= 8 ? ROUGE : uv >= 6 ? ORANGE : uv >= 3 ? AMBRE : GRIS;
    out += pas('mdi:sun-wireless-outline', esc(fr(uv, 0)),
               'UV ' + esc(A.uv_tx || ''), uc, window.meGeste(SRC.uv));
  }
  var lux = nb(A.lux);
  if (lux !== null) {
    out += pas('mdi:brightness-5',
               lux >= 1000 ? esc(fr(lux / 1000, 1)) + '<small>k</small>'
                           : esc(fr(lux, 0)),
               'lux', AMBRE, window.meGeste(SRC.lux));
  }
  var sol = nb(A.solaire);
  if (sol !== null) {
    out += pas('mdi:solar-power-variant-outline', esc(fr(sol, 0)),
               'W/m²', AMBRE, window.meGeste(SRC.solaire));
  }
  var hr = nb(A.hr_ext);
  if (hr !== null) out += pas('mdi:water-percent', esc(fr(hr, 0)) + '<small>%</small>',
                              'humidité', CYAN, window.meGeste(SRC.hr_ext));
  var tt = nb(A.tend_temp);
  if (tt !== null && Math.abs(tt) >= 0.05) {
    out += pas(tt > 0 ? 'mdi:trending-up' : 'mdi:trending-down',
               (tt > 0 ? '+' : '−') + esc(fr(Math.abs(tt), 1))
               + '<small>°/h</small>',
               tt > 0 ? 'ça se réchauffe' : 'ça se rafraîchit',
               GRIS, window.meGeste(SRC.tend_temp));
  }
  var ro = nb(A.rosee);
  if (ro !== null) {
    out += pas('mdi:thermometer-water', esc(fr(ro, 1)) + '<small>°</small>',
               ro >= 20 ? 'rosée · très lourd'
             : ro >= 18 ? 'rosée · lourd' : 'rosée', CYAN,
               window.meGeste(SRC.rosee));
  }
  var MOTS = {none: 0, aucun: 0, nul: 0, low: 1, faible: 1, bas: 1,
              moderate: 2, modere: 2, 'modéré': 2, moyen: 2,
              high: 3, eleve: 3, 'élevé': 3, fort: 3,
              very_high: 4, 'very high': 4, 'très élevé': 4,
              'tres eleve': 4, extreme: 4, 'extrême': 4};
  var ETIQ = ['', 'faible', 'modéré', 'élevé', 'très élevé'];
  var COUL = [GRIS, VERT, AMBRE, ORANGE, ROUGE];
  var pol = '';
  (V.pollens || []).forEach(function (p) {
    var e = p.id ? S[p.id] : null;
    if (!e || e.state === 'unavailable' || e.state === 'unknown') return;
    var brut = String(e.state).toLowerCase().trim();
    var lvl = null;
    if (MOTS[brut] !== undefined) {
      lvl = MOTS[brut];
    } else {
      var v = parseFloat(brut);
      if (isFinite(v)) lvl = Math.max(0, Math.min(4, Math.round(v)));
    }
    if (lvl === null || lvl <= 0) return;
    pol += '<span class="me-pa" style="--pc: ' + COUL[lvl] + ';"'
        +    ' title="' + esc(p.nom || p.id) + ' · ' + ETIQ[lvl] + '">'
        +    '<ha-icon icon="' + esc(p.ico || 'mdi:flower-pollen') + '"></ha-icon>'
        +    '<b>' + esc(p.nom || p.id) + '</b><i>' + ETIQ[lvl] + '</i>'
        +  '</span>';
  });
  if (pol) out += '<span class="me-pas-sep"></span>' + pol;
  return out ? '<div class="me-pas">' + out + '</div>' : '';

 }
 const rendered = {heros: heros(), essentiels: essentiels(), sect1: sect1(), sect2: sect2(), sect3: sect3(), bilan: bilan(), courbe: courbe(), jours: jours(), tuiles: tuiles(), pastilles: pastilles()};
 const gauge = rendered.heros.indexOf('<div class="me-jauge">');
 return {...rendered, comfort: gauge < 0 ? "" : rendered.heros.slice(gauge, -6)};
}
